routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\StateController;
use App\Http\Controllers\Auth\AuthController;
use App\Http\Controllers\DashboardController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::get('login', [AuthController::class, 'login'])->name('login');
Route::post('login', [AuthController::class, 'authenticate']);

Route::middleware(['auth'])->group(function () {

    Route::get('/', [DashboardController::class,'dashboard'])->name('dashboard');
    Route::resource('states', StateController::class);
    Route::resource('users', UserController::class);

    Route::get('logout', [AuthController::class, 'logout'])->name('logout');
});

app/Models/State.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class State extends Model
{
    use HasFactory;

    protected $fillable = [
        'cvegeo',
        'cve_agee',
        'nom_agee',
        'nom_abrev',
        'pob',
        'pob_fem',
        'pob_mas',
        'viv',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use App\Models\State;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function dashboard() : View{
        return \View::make('admin.dashboard');
    }
}

app/Http/Controllers/StateController.php
<?php

namespace App\Http\Controllers;

use stdClass;
use Exception;
use App\Models\State;
use App\Http\Helper\Inegi;
use Illuminate\Http\Request;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Response;

class StateController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        $items = State::orderBy('nom_agee')->get();
        return \View::make('admin.states.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $data = Inegi::getStates();

        $states = [];
        foreach ($data->datos as $state) {
            $states[] = State::updateOrCreate([
                'nom_agee' => $state->nom_agee,
                'nom_abrev' => $state->nom_abrev,
            ], [
                'cve_agee' => $state->cve_agee,
                'cvegeo' => $state->cvegeo,
                'pob' => $state->pob,
                'pob_fem' => $state->pob_fem,
                'pob_mas' => $state->pob_mas,
                'viv' => $state->viv,
            ]);
        }

        session()->flash('success');
        return Response::make(['code' => 1]);
        // return Redirect::route('states.index')->with('success');
    }

    /**
     * Display the specified resource.
     */
    public function show(State $state): View
    {
        return \View::make('admin.states.show', ['item' => $state]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(State $state)
    {
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, State $state)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(State $state)
    {
        $state->delete();
        session()->flash('success');
        return Response::make(['code' => 1]);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index() : View
    {
        $items = User::get();
        return \View::make('admin.users.index', ['items' => $items]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(User $user)
    {
        //
    }
}

resources/views/admin/dashboard.blade.php
@extends('layouts.master_admin')

@section('content')
<!--begin::Row-->
<div class="row gx-5 gx-xl-10">
	<!--begin::Col-->
	<div class="col-xl-4">

	</div>
	<!--end::Col-->
</div>
<!--end::Row-->
@endsection

resources/views/admin/states/index.blade.php
@extends('layouts.master_admin')
@section('content')
<div class="row">
    <div class="d-flex flex-wrap flex-stack pb-7">
        <div class="d-flex flex-wrap align-items-center my-1">
            <h3 class="fw-bolder fs-3 me-5 my-1">Listado de Estados</h3>
            <div class="d-flex align-items-center position-relative my-1">
                <span class="svg-icon svg-icon-3 position-absolute ms-3">
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                        <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="black" />
                        <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="black" />
                    </svg>
                </span>
                <input type="text" id="kt_filter_search" class="form-control form-control-sm border-body bg-body w-200px ps-10" placeholder="Search" />
            </div>
        </div>
        <div class="d-flex flex-wrap my-1">
            <div class="d-flex my-0">
                <a href="#" onclick="reloadStatesApi('{{route('states.store')}}')" class="btn btn-primary btn-sm">API Import</a>
            </div>
        </div>
    </div>
    <div class="tab-content">
        <div id="kt_project_users_table_pane" class="tab-pane fade show active">
            <div class="card card-flush">
                <div class="card-body pt-0">
                    <div class="table-responsive">
                        <table id="kt_tables" class="table table-row-bordered table-row-dashed gy-4 align-middle fw-bolder">
                            <thead class="fs-7 text-gray-400 text-uppercase">
                                <tr>
                                    <th class="min-w-50px">Nombre del área</th>
                                    <th class="min-w-50px">Nombre abreviado</th>
                                    <th class="min-w-50px text-end">Acciones</th>
                                </tr>
                            </thead>
                            <tbody class="fs-6">
                                @foreach ($items as $i)
                                    <tr>
                                        <td>
                                            <span class="text-gray-700 fw-bold text-muted d-block fs-7">
                                                {{$i->nom_agee}}
                                            </span>
                                        </td>
                                        <td>
                                            <span class="text-gray-700 fw-bold text-muted d-block fs-7">
                                                {{$i->nom_abrev}}
                                            </span>
                                        </td>
                                        <td class="text-end">
                                            <a href="{{route('states.show',$i->id)}}" class="btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1">
                                                <!--begin::Svg Icon | path: icons/duotune/art/art005.svg-->
                                                <span class="svg-icon svg-icon-3">
                                                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                        <path d="M21.7 18.9L18.6 15.8C17.9 16.9 16.9 17.9 15.8 18.6L18.9 21.7C19.3 22.1 19.9 22.1 20.3 21.7L21.7 20.3C22.1 19.9 22.1 19.3 21.7 18.9Z" fill="currentColor"/>
                                                        <path opacity="0.3" d="M11 20C6 20 2 16 2 11C2 6 6 2 11 2C16 2 20 6 20 11C20 16 16 20 11 20ZM11 4C7.1 4 4 7.1 4 11C4 14.9 7.1 18 11 18C14.9 18 18 14.9 18 11C18 7.1 14.9 4 11 4ZM8 11C8 9.3 9.3 8 11 8C11.6 8 12 7.6 12 7C12 6.4 11.6 6 11 6C8.2 6 6 8.2 6 11C6 11.6 6.4 12 7 12C7.6 12 8 11.6 8 11Z" fill="currentColor"/>
                                                    </svg>
                                                </span>
                                                <!--end::Svg Icon-->
                                            </a>
                                            <a href="#" onclick="removeItem('{{route('states.destroy',$i->id)}}')" class="btn btn-icon btn-bg-light btn-active-color-primary btn-sm">
                                                <!--begin::Svg Icon | path: icons/duotune/general/gen027.svg-->
                                                <span class="svg-icon svg-icon-3">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                                                        <path d="M5 9C5 8.44772 5.44772 8 6 8H18C18.5523 8 19 8.44772 19 9V18C19 19.6569 17.6569 21 16 21H8C6.34315 21 5 19.6569 5 18V9Z" fill="currentColor" />
                                                        <path opacity="0.5" d="M5 5C5 4.44772 5.44772 4 6 4H18C18.5523 4 19 4.44772 19 5V5C19 5.55228 18.5523 6 18 6H6C5.44772 6 5 5.55228 5 5V5Z" fill="currentColor" />
                                                        <path opacity="0.5" d="M9 4C9 3.44772 9.44772 3 10 3H14C14.5523 3 15 3.44772 15 4V4H9V4Z" fill="currentColor" />
                                                    </svg>
                                                </span>
                                                <!--end::Svg Icon-->
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('custom-scripts')
    <script src="{{ asset('panel_assets/js/tables.js') }}"></script>
@endpush

resources/views/admin/states/show.blade.php
@extends('layouts.master_admin')

@section('title')
    Usuario
@endsection

@section('content')
    <div class="row">
        <div class="col-12 col-lg-12">
            <div class="card h-md-100">
                <div class="card-header">
                    <h3 class="card-title">
                        Información General
                    </h3>
                    <div class="card-toolbar">
                        <div class="justify-content-center">
                        </div>
                    </div>
                </div>
                <div class="card-body pt-5">
                    <div class="row">
                        <div class="col-12 col-xl-4">
                            <div class="row mb-8">
                                <div class="col-xl-12">
                                    <div class="fs-6 fw-bold">
                                        <label for="name" class="required form-label">Clave</label>
                                    </div>
                                </div>
                                <div class="col-xl-12">
                                    <input type="text" class="form-control" placeholder="Nombre" id="name" name="name" value="{{$item->cvegeo}}" readonly/>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-xl-4">
                            <div class="row mb-8">
                                <div class="col-xl-12">
                                    <div class="fs-6 fw-bold">
                                        <label for="name" class="required form-label">Nombre</label>
                                    </div>
                                </div>
                                <div class="col-xl-12">
                                    <input type="text" class="form-control" placeholder="Nombre" id="name" name="name" value="{{$item->nom_agee}}" readonly/>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-xl-4">
                            <div class="row mb-8">
                                <div class="col-xl-12">
                                    <div class="fs-6 fw-bold">
                                        <label for="name" class="required form-label">Nombre Abreviado</label>
                                    </div>
                                </div>
                                <div class="col-xl-12">
                                    <input type="text" class="form-control" placeholder="Nombre" id="name" name="name" value="{{$item->nom_abrev}}" readonly/>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-xl-4">
                            <div class="row mb-8">
                                <div class="col-xl-12">
                                    <div class="fs-6 fw-bold">
                                        <label for="name" class="required form-label">Población</label>
                                    </div>
                                </div>
                                <div class="col-xl-12">
                                    <input type="text" class="form-control" placeholder="Nombre" id="name" name="name" value="{{$item->pob}}" readonly/>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-xl-4">
                            <div class="row mb-8">
                                <div class="col-xl-12">
                                    <div class="fs-6 fw-bold">
                                        <label for="name" class="required form-label">Población Femenina</label>
                                    </div>
                                </div>
                                <div class="col-xl-12">
                                    <input type="text" class="form-control" placeholder="Nombre" id="name" name="name" value="{{$item->pob_fem}}" readonly/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@push('custom-scripts')
<script>
    $('#city_id').on("change",function(){
        $('#neighboardhood_id option').remove();
        $.ajax({
            method:'GET',
            url: "/cities/"+$(this).val()+"/neighboardhoods"
        }).done(function(response){
            var opt = new Option("Selecciona una Comuna", null);
            $('#neighboardhood_id').append(opt);

            response.neighboardhoods.forEach(n => {
                var o = new Option(n.name, n.id);
                $("#neighboardhood_id").append(o)
            });
        });
    });
</script>
@endpush

resources/views/admin/users/index.blade.php
@extends('layouts.master_admin')
@section('content')
<div class="row">
    <div class="d-flex flex-wrap flex-stack pb-7">
        <div class="d-flex flex-wrap align-items-center my-1">
            <h3 class="fw-bolder fs-3 me-5 my-1">Listado de Usuarios</h3>
            <form action="{{ route('users.index') }}" method="GET">
                <div class="d-flex align-items-center position-relative my-1">
                    <span class="svg-icon svg-icon-3 position-absolute ms-3">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none">
                            <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="black" />
                            <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="black" />
                        </svg>
                    </span>


                <input type="text" id="kt_filter_search" class="form-control form-control-sm border-body bg-body w-200px ps-10" placeholder="Search" />

                </div>
            </form>
        </div>
        <div class="d-flex flex-wrap my-1">
            {{-- <div class="d-flex my-0">
                <a href="{{route('users.create')}}" class="btn btn-primary btn-sm">Nuevo</a>
            </div> --}}
        </div>
    </div>
    <div class="tab-content">
        <div id="kt_project_users_table_pane" class="tab-pane fade show active">
            <div class="card card-flush">
                <div class="card-body pt-0">
                    <div class="table-responsive">
                        <table id="kt_tables" class="table table-row-bordered table-row-dashed gy-4 align-middle fw-bolder">
                            <thead class="fs-7 text-gray-400 text-uppercase">
                                <tr>
                                    <th class="min-w-50px">ID</th>
                                    <th class="min-w-50px">Nombre</th>
                                    <th class="min-w-50px">Email</th>
                                    <th class="min-w-50px">Creado</th>
                                    {{-- <th class="min-w-50px text-end">Acciones</th> --}}
                                </tr>
                            </thead>
                            <tbody class="fs-6">
                                @foreach ($items as $i)
                                    <tr>
                                        <td>
                                            <span class="text-gray-700 fw-bold text-muted d-block fs-7">
                                                {{$i->id}}
                                            </span>
                                        </td>
                                        <td>
                                            <span class="text-gray-700 fw-bold text-muted d-block fs-7">
                                                {{$i->name}}
                                            </span>
                                        </td>
                                        <td>
                                            <span class="text-gray-700 fw-bold text-muted d-block fs-7">
                                                {{$i->email}}
                                            </span>
                                        </td>
                                        <td>
                                            <span class="text-gray-700 fw-bold text-muted d-block fs-7">
                                                {{$i->created_at}}
                                            </span>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('custom-scripts')
    <script src="{{ asset('panel_assets/js/tables.js') }}"></script>
@endpush

resources/views/layouts/alerts.blade.php
<script>
    @if (session()->exists('success'))
        success();
    @endif
    @if (session()->exists('errors'))
        Swal.fire({
            icon: 'warning',
            title: 'Algo salió, intentelo mas tarde',
            html: '{!! implode('', $errors->all('<div>:message</div><br/>')) !!}',
            confirmButtonColor: '#385670',
        })
    @endif

    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    function removeItem(route) {
        Swal.fire({
            icon: 'info',
            title: 'Advertencia',
            text: '¿Estás seguro de eliminar el registro?',
            showCancelButton: true,
            confirmButtonText: "Aceptar",
            cancelButtonText: "Cancelar",
            confirmButtonColor: '#385670'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    type: "DELETE",
                    url: route,
                }).done(function(msg) {
                    location.reload();
                }).fail(function(msg) {

                });
            } else if (result.isDenied) {

            }
        });
    }

    function reloadStatesApi(route) {
        Swal.fire({
            icon: 'info',
            title: 'Advertencia',
            text: 'Se reiniciará la carga de la información actual',
            showCancelButton: true,
            confirmButtonText: "Aceptar",
            cancelButtonText: "Cancelar",
            confirmButtonColor: '#385670'
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    type: "POST",
                    url: route,
                }).done(function(msg) {
                    location.reload();
                }).fail(function(msg) {

                });
            } else if (result.isDenied) {

            }
        });
    }

    function loading() {
        Swal.fire({
            title: 'Cargando!',
            html: 'Por favor espere',
            timerProgressBar: true,
            allowOutsideClick: false,
            didOpen: () => {
                Swal.showLoading()
            },
            willClose: () => {}
        }).then((result) => {

        });
    }

    function success() {
        Swal.fire({
            icon: 'success',
            title: 'Éxito',
            text: '',
            confirmButtonColor: '#385670',
        })
    }
</script>

resources/views/layouts/master_auth.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />
    <link href="{{ asset('panel_assets/plugins/global/plugins.bundle.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('panel_assets/css/style.bundle.css') }}" rel="stylesheet" type="text/css" />
    <!-- Scripts -->
</head>
<!--end::Head-->
<!--begin::Body-->

<body id="kt_body" class="app-blank app-blank bgi-size-cover bgi-position-center bgi-no-repeat">
    <!--begin::Theme mode setup on page load-->
    <script>
        var defaultThemeMode = "light";
        var themeMode;
        if (document.documentElement) {
            if (document.documentElement.hasAttribute("data-theme-mode")) {
                themeMode = document.documentElement.getAttribute("data-theme-mode");
            } else {
                if (localStorage.getItem("data-theme") !== null) {
                    themeMode = localStorage.getItem("data-theme");
                } else {
                    themeMode = defaultThemeMode;
                }
            }
            if (themeMode === "system") {
                themeMode = window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
            }
            document.documentElement.setAttribute("data-theme", themeMode);
        }
    </script>
    <!--end::Theme mode setup on page load-->
    <!--begin::Root-->
    <div class="d-flex flex-column flex-root" id="kt_app_root">
        <!--begin::Page bg image-->
        <style>
            body {
                background-image: url('/panel_assets/media/auth/bg3-dark.jpg');
            }

            [data-theme="dark"] body {
                background-image: url('/panel_assets/media/auth/bg4-dark.jpg');
            }
        </style>
        <!--end::Page bg image-->
        @yield('content')
    </div>
    <!--end::Root-->
    <!--begin::Javascript-->
    <script>
        var hostUrl = "panel_assets/";
    </script>
    <!--begin::Global Javascript Bundle(mandatory for all pages)-->
    <script src="{{ asset('panel_assets/plugins/global/plugins.bundle.js') }}"></script>
    <script src="{{ asset('panel_assets/js/scripts.bundle.js') }}"></script>
    <!--end::Global Javascript Bundle-->
    <!--end::Javascript-->
</body>
<!--end::Body-->

</html>

resources/views/layouts/toolbar.blade.php
<!--begin::Toolbar-->
<div id="kt_app_toolbar" class="app-toolbar py-1 py-lg-2">
    <!--begin::Toolbar container-->
    <div id="kt_app_toolbar_container" class="app-container container-fluid d-flex flex-stack">
        <!--begin::Page title-->
        <div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
            <!--begin::Breadcrumb-->
            <ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0 pt-1">
                @foreach ($breadcrumbs as $b)
                    <!--begin::Item-->
                    <li class="breadcrumb-item text-muted">
                        <a href="#" class="text-muted text-hover-primary">{{ $b['title'] }}</a>
                    </li>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <li class="breadcrumb-item">
                        <span class="bullet bg-gray-400 w-5px h-2px"></span>
                    </li>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <li class="breadcrumb-item text-muted">Dashboards</li>
                    <!--end::Item-->
                @endforeach
            </ul>
            <!--end::Breadcrumb-->
        </div>
        <!--end::Page title-->
        {{-- <!--begin::Actions-->
        <div class="d-flex align-items-center gap-2 gap-lg-3">
            <!--begin::Secondary button-->
            <a href="#" class="btn btn-sm fw-bold bg-body btn-color-gray-700 btn-active-color-primary" data-bs-toggle="modal" data-bs-target="#kt_modal_create_app">Rollover</a>
            <!--end::Secondary button-->
            <!--begin::Primary button-->
            <a href="#" class="btn btn-sm fw-bold btn-primary" data-bs-toggle="modal" data-bs-target="#kt_modal_new_target">Add Target</a>
            <!--end::Primary button-->
        </div>
        <!--end::Actions--> --}}
    </div>
    <!--end::Toolbar container-->
</div>
<!--end::Toolbar-->